In [32]:

import json

with open(r"C:\Users\157336\Python Scripts\Tdqeq\result.json") as file:
    
    s= json.loads(file.read())

In [33]:
d= [(table['html'], table['detection_confidence'])
    for table in s
]

<html><body><table class="5.5 Electrical Characteristics CTR = CTS = Open, RESET pull-up resistor (R pull-up ) = 100 kΩ to V DD , output reset load (C LOAD ) = 10 pF and over the"><tr><td colspan="2">T A = 25 ℃</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="2">PARAMETER</td><td>TEST CONDITIONS</td><td>MIN</td><td>TYP</td><td>MAX</td><td>UNIT</td></tr><tr><td colspan="2">COMMON PARAMETERS</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>V DD</td><td>Input supply voltage (Open Drain Low and Push Pull Low)</td><td></td><td>0.85</td><td></td><td>6</td><td>V</td></tr><tr><td>V DD</td><td>Input supply voltage (Push Pull High)</td><td>for all output configs</td><td>1</td><td></td><td>6</td><td>V</td></tr><tr><td>V IT– (1)</td><td>Negative-going input threshold range Negative-going input threshold for</td><td></td><td>0.8</td><td></td><td>5.4</td><td>V</td></tr><tr><td>V ADJ-VIT–</td><td>adjustable sense threshold version</td><td>IT– = 0.505 V (ADJ version) or 0.8 V to</td><td></td><td>0.505</td><td></td><td>V</td></tr><tr><td>V IT– accuracy</td><td>Negative-going input threshold accuracy</td><td>V 1.7 V (Fixed threshold) V = 1.8 V to 5.4 V (Fixed threshold)</td><td>–2.5</td><td>±0.5</td><td>2.5</td><td>%</td></tr><tr><td>V HYS</td><td>Hysteresis</td><td>IT–</td><td>–2</td><td>±0.5</td><td>2</td><td></td></tr><tr><td rowspan="3">I SENSE</td><td rowspan="3">on V IT– Current into Sense pin, fixed threshold</td><td>V IT– = 0.505 V and 0.8 V</td><td>3</td><td>5</td><td>8</td><td>%</td></tr><tr><td>V IT– = 0.9 V to 5.4 V</td><td>3</td><td>5</td><td>7</td><td>%</td></tr><tr><td>V DD = V SENSE = 6 V</td><td></td><td>0.025</td><td>0.1</td><td>µA</td></tr><tr><td>I</td><td>Current into Sense pin, ADJ version Supply current into VDD pin when sense</td><td>V DD = V SENSE = 6 V V DD = V SENSE = 6 V</td><td></td><td>0.025</td><td>0.05</td><td>µA</td></tr><tr><td>DD</td><td>pin is separate Voltage threshold to stop CTS capacitor</td><td>V IT– = 0.505 V and 0.8 V to 5.4 V</td><td>0.73 *</td><td>0.125</td><td>1</td><td>µA</td></tr><tr><td>V TH_CTS</td><td>charge and assert RESET Voltage threshold to stop CTR capacitor</td><td></td><td>0.73</td><td>V DD *</td><td></td><td>V</td></tr><tr><td>V TH_CTR R CTS</td><td>charge and deassert RESET CTS pin internal pull up resistance</td><td></td><td></td><td>V DD</td><td></td><td>V</td></tr><tr><td>R CTR</td><td>CTR pin internal pull up resistance</td><td></td><td></td><td>500 500</td><td></td><td>kΩ kΩ</td></tr><tr><td colspan="7">TPS3899DL (Open-drain active-low)</td></tr><tr><td>V POR</td><td>Power on reset voltage (2)</td><td>V OL(max) = 300 mV I = 15 µA</td><td></td><td>700</td><td></td><td>mV</td></tr><tr><td rowspan="2">V OL</td><td rowspan="2">Low level output voltage</td><td>RESET(Sink) V DD = 0.85 V</td><td colspan="2"></td><td></td><td>mV</td></tr><tr><td>I RESET(Sink) = 15 µA V DD = 3.3 V</td><td colspan="2"></td><td>300</td><td></td></tr><tr><td></td><td></td><td>I RESET(Sink) = 2 mA V DD = V PULLUP = 6 V, T A = –40 ℃ to 85 ℃</td><td colspan="2"></td><td>300</td><td>mV</td></tr><tr><td>I lkg(OD) TPS3899PL</td><td>Open-Drain output leakage current</td><td>V DD = V PULLUP = 6 V</td><td colspan="2">10 10</td><td>100 350</td><td>nA nA</td></tr><tr><td colspan="8">(Push-pull active-low)</td></tr><tr><td>V POR</td><td>Power on reset voltage (2)</td><td>V OL(max) = 300 mV I RESET(Sink) = 15 µA</td><td colspan="2"></td><td>700</td><td>mV</td></tr><tr><td rowspan="2">V OL</td><td rowspan="2">Low level output voltage</td><td>V DD = 0.85 V I = 15 µA</td><td colspan="2"></td><td>300</td><td>mV</td></tr><tr><td>RESET(Sink) V DD = 3.3 V I = 2 mA</td><td colspan="2"></td><td></td><td></td></tr><tr><td rowspan="4">V OH</td><td rowspan="4">High level output voltage I</td><td>RESET(Sink) V DD = 1.8 V</td><td colspan="2"></td><td>300</td><td>mV</td></tr><tr><td>I RESET(Source) = 500 µA V DD = 3.3 V</td><td colspan="2">0.8V DD</td><td></td><td>V</td></tr><tr><td>RESET(Source) = 500 µA = 6 V</td><td colspan="2">0.8V DD</td><td></td><td>V</td></tr><tr><td>V DD I RESET(Source) = 2 mA</td><td colspan="2">0.8V DD</td><td></td><td>V</td></tr></table></body></html>

<html><body><table class="Conductor"><tr><td>Element</td><td>No. of Elements</td><td>Size</td><td>Stranding</td><td>Material</td></tr><tr><td>Conductor(s)</td><td>4</td><td>22</td><td>Solid</td><td>BC - Bare Copper</td></tr></table></body></html>

<html><body><table class="CHARACTERISTICS - JU7070B 36‑V K CLASS"><tr><td>Characteristics</td><td>Unit Minimum</td><td>Typical</td><td>Maximum</td></tr><tr><td>Thermal resistance, junction to solder point</td><td>°C/W</td><td>0.6</td><td></td></tr><tr><td>Viewing angle (FWHM)</td><td>degrees</td><td>115</td><td></td></tr><tr><td>Temperature coefficient of voltage</td><td>mV/°C</td><td>-12.5</td><td></td></tr><tr><td>ESD withstand voltage (HBM per Mil-Std-883L)</td><td></td><td>Class 2</td><td></td></tr><tr><td>DC forward current</td><td>mA</td><td></td><td>400</td></tr><tr><td>Reverse voltage</td><td>V</td><td></td><td>5</td></tr><tr><td>Forward voltage (@ 233 mA, 25 °C)</td><td>V</td><td>35.4</td><td>36.5</td></tr><tr><td>LED junction temperature</td><td>°C</td><td></td><td>125</td></tr><tr><td>Operating temperature</td><td>°C -40</td><td></td><td>105</td></tr></table></body></html>

<html><body><table class="area and indoor downlights. PRODUCT SUMMARY"><tr><td rowspan="2">Product</td><td rowspan="2">Power Class</td><td rowspan="2">Test Temperature</td><td rowspan="2">Test Current</td><td rowspan="2">Typical Forward Voltage</td><td colspan="2">4000 K, 70 CRI</td><td rowspan="2">Maximum Current</td></tr><tr><td>Typical Flux</td><td>Typical Efficacy</td></tr><tr><td>JU7070B 12‑V K Class</td><td>8 W</td><td>25 ° C</td><td>700 mA</td><td>11.8 V</td><td>1580 lm</td><td>191.5 LPW</td><td>1200 mA</td></tr><tr><td>JU7070B 36‑V K Class</td><td>8 W</td><td>25 ° C</td><td>233 mA</td><td>35.4 V</td><td>1580 lm</td><td>191.5 LPW</td><td>400 mA</td></tr></table></body></html>

<html><body><table class="FLUX CHARACTERISTICS, ORDER CODES AND BINS - JU7070B 36‑V K CLASS (I = 233 mA, T = 25 °C) F j The following table provides order codes for J Series JU7070B 36‑V K Class LEDs. For a complete description of nomenclature, please see the Order Code and Bin Code Formats section (page 3). For definitions of the chromaticity the Performance Groups - Chromaticity section (page 15)."><tr><td>Nominal CCT</td><td>Minimum CRI</td><td>Minimum Luminous Flux (lm) @ 25 ° C</td><td>Typical Luminous Flux (lm) @ 25 ° C</td><td>Typical Luminous Flux (lm) @ 85 ° C*</td><td>parts</td></tr><tr><td rowspan="3">6500 K</td><td>70</td><td>1500</td><td>1580</td><td>1438</td><td>JU7070BWT-K-B65EN0000-N0000001</td></tr><tr><td>80</td><td>1400</td><td>1475</td><td>1342</td><td>JU7070BWT-K-H65EN0000-N0000001</td></tr><tr><td>90</td><td>1250</td><td>1320</td><td>1201</td><td>JU7070BWT-K-U65EN0000-N0000001</td></tr><tr><td rowspan="3">5700 K</td><td>70</td><td>1500</td><td>1580</td><td>1438</td><td>JU7070BWT-K-B57EN0000-N0000001</td></tr><tr><td>80</td><td>1400</td><td>1475</td><td>1342</td><td>JU7070BWT-K-H57EN0000-N0000001</td></tr><tr><td>90</td><td>1250</td><td>1320</td><td>1201</td><td>JU7070BWT-K-U57EN0000-N0000001</td></tr><tr><td rowspan="3">5000 K</td><td>70</td><td>1500</td><td>1580</td><td>1438</td><td>JU7070BWT-K-B50EN0000-N0000001</td></tr><tr><td>80</td><td>1400</td><td>1475</td><td>1342</td><td>JU7070BWT-K-H50EN0000-N0000001</td></tr><tr><td>90</td><td>1250</td><td>1320</td><td>1201</td><td>JU7070BWT-K-U50EN0000-N0000001</td></tr><tr><td rowspan="3">4000 K</td><td>70</td><td>1500</td><td>1580</td><td>1438</td><td>JU7070BWT-K-B40EN0000-N0000001</td></tr><tr><td>80</td><td>1400</td><td>1475</td><td>1342</td><td>JU7070BWT-K-H40EN0000-N0000001</td></tr><tr><td>90</td><td>1250</td><td>1320</td><td>1201</td><td>JU7070BWT-K-U40EN0000-N0000001</td></tr><tr><td rowspan="3">3500 K</td><td>70</td><td>1450</td><td>1525</td><td>1388</td><td>JU7070BWT-K-B35EN0000-N0000001</td></tr><tr><td>80</td><td>1350</td><td>1418</td><td>1290</td><td>JU7070BWT-K-H35EN0000-N0000001</td></tr><tr><td>90</td><td>1200</td><td>1265</td><td>1151</td><td>JU7070BWT-K-U35EN0000-N0000001</td></tr><tr><td rowspan="3">3000 K</td><td>70</td><td>1400</td><td>1495</td><td>1360</td><td>JU7070BWT-K-B30EN0000-N0000001</td></tr><tr><td>80</td><td>1300</td><td>1390</td><td>1265</td><td>JU7070BWT-K-H30EN0000-N0000001</td></tr><tr><td>90</td><td>1150</td><td>1240</td><td>1128</td><td>JU7070BWT-K-U30EN0000-N0000001</td></tr><tr><td rowspan="3">2700 K</td><td>70</td><td>1400</td><td>1465</td><td>1333</td><td>JU7070BWT-K-B27EN0000-N0000001</td></tr><tr><td>80</td><td>1300</td><td>1362</td><td>1239</td><td>JU7070BWT-K-H27EN0000-N0000001</td></tr><tr><td>90</td><td>1100</td><td>1200</td><td>1092</td><td>JU7070BWT-K-U27EN0000-N0000001</td></tr><tr><td rowspan="3">2200 K</td><td>70</td><td>1250</td><td>1350</td><td>1229</td><td>JU7070BWT-K-B22EN0000-N0000001</td></tr><tr><td>80</td><td>1150</td><td>1228</td><td>1117</td><td>JU7070BWT-K-H22EN0000-N0000001</td></tr><tr><td>90</td><td>1000</td><td>1081</td><td>984</td><td>JU7070BWT-K-U22EN0000-N0000001</td></tr></table></body></html>

<html><body><table class="0.39 0.38 0.43 0.44 0.45 0.46 0.47 0.48 0.49 CCx"><tr><td rowspan="2">CCT</td><td rowspan="2">MacAdam Ellipse</td><td rowspan="2">Included Bins</td><td colspan="2">Center Point</td><td>Major Axis</td><td>Minor Axis</td><td rowspan="2">Rotation Angle (°)</td></tr><tr><td>x</td><td>y</td><td>a</td><td>b</td></tr><tr><td rowspan="2">2700 K</td><td>3-step</td><td>8GA, 8GB</td><td>0.4578</td><td>0.4101</td><td>0.00810</td><td>0.00420</td><td>53.70</td></tr><tr><td>Kitted 3-step</td><td>8GA, 8GB, 8EA, 8EB, 8EC, 8ED</td><td>0.4578</td><td>0.4101</td><td>0.01350</td><td>0.00700</td><td>53.70</td></tr></table></body></html>

<html><body><table class="Voltage"><tr><td>UL Voltage</td><td>Rating</td></tr><tr><td>300 V</td><td></td></tr></table></body></html>

<html><body><table class="Moisture Sensitivity Cree Venture recommends keeping J Series 7070 LEDs in the provided, resealable moisture-barrier packaging (MBP) until immediately prior to soldering. Unopened MBP that contains J Series 7070 LEDs does not need special storage for moisture sensitivity."><tr><td rowspan="2">Moisture Sensitivity Level</td><td rowspan="2">Temp.</td><td colspan="5">Maximum Percent Relative Humidity</td></tr><tr><td>50%</td><td>60%</td><td>70%</td><td>80%</td><td>90%</td></tr><tr><td>Level 3</td><td>35 ºC</td><td>8</td><td>5</td><td>1</td><td>0.5</td><td>0.5</td></tr><tr><td>Level 3</td><td>30 ºC</td><td>11</td><td>7</td><td>1</td><td>1</td><td>1</td></tr><tr><td>Level 3</td><td>25 ºC</td><td>14</td><td>10</td><td>2</td><td>1</td><td>1</td></tr><tr><td>Level 3</td><td>20 ºC</td><td>20</td><td>13</td><td>2</td><td>1</td><td>1</td></tr></table></body></html>

<html><body><table class="OPERATING ELECTRICAL CHARACTERISTICS T A = 25 ° C V S = ± 5.0V unless otherwise specified"><tr><td rowspan="2">Parameter</td><td rowspan="2"></td><td colspan="3">2704A</td><td colspan="3">2704B</td><td colspan="3">2704</td><td rowspan="2"></td><td rowspan="2">Test Conditions</td></tr><tr><td>Symbol</td><td>Min</td><td>± Typ</td><td>± Max Min</td><td>Typ</td><td>± 6.0 Max</td><td>Min</td><td>Typ</td><td>Max Unit</td></tr><tr><td>Supply Voltage</td><td>V S V +</td><td>3.25 6.5</td><td></td><td>6.0 12.0</td><td>3.25 6.5</td><td></td><td>± 12.0</td><td>3.25 6.5</td><td></td><td>6.0 12.0</td><td>V V</td><td>Dual Supply Single Supply</td></tr><tr><td>Input Offset Voltage</td><td>V OS</td><td></td><td></td><td>1.0 1.5</td><td></td><td></td><td>2.0 3.0</td><td></td><td></td><td>5.0 6.0</td><td>mV mV</td><td>R S ≤ 100K Ω 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>Input Offset Current</td><td>OS</td><td></td><td>1.0</td><td>15 240</td><td></td><td>1.0</td><td>15 240</td><td></td><td>1.0</td><td>15 240</td><td>pA pA</td><td>T A = 25 ° C 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>Input Bias Current</td><td>B</td><td></td><td>1.0</td><td>20 300</td><td></td><td>1.0</td><td>20 300</td><td></td><td>1.0</td><td>20 300</td><td>pA pA</td><td>T A = 25 ° C 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>Input Voltage Range</td><td>V IR</td><td>-5.3</td><td></td><td>5.3</td><td>-5.3</td><td></td><td>5.3</td><td>-5.3</td><td></td><td>5.3</td><td>V</td><td></td></tr><tr><td>Input Resistance</td><td>R IN</td><td></td><td>10 12</td><td></td><td></td><td>10 12</td><td></td><td></td><td>10 12</td><td></td><td>Ω</td><td></td></tr><tr><td>Input Offset Voltage Drift</td><td>TCV OS</td><td></td><td>5</td><td></td><td></td><td>5</td><td></td><td></td><td>5</td><td></td><td>µ V/</td><td>R S ≤ 100K Ω</td></tr><tr><td>Power Supply Rejection Ratio</td><td>PSRR</td><td>65</td><td>80</td><td></td><td>65</td><td>80</td><td></td><td>60</td><td>80</td><td></td><td>dB</td><td>R S ≤ 100K Ω 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>Common Mode Rejection Ratio</td><td>CMRR</td><td>65</td><td>83</td><td></td><td>65</td><td>83</td><td></td><td>60</td><td>83</td><td></td><td>dB</td><td>R S ≤ 100K Ω 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>Large Signal Voltage Gain</td><td>V</td><td>15</td><td>28 100</td><td></td><td>15</td><td>28 100</td><td></td><td>10</td><td>28 100</td><td></td><td>V/mV V/mV</td><td>R L = 100K Ω R L ≥ 1M Ω</td></tr><tr><td rowspan="2">Output Voltage Range</td><td>V O low V O high low</td><td>4.90</td><td>-4.96 4.95</td><td>-4.90</td><td>4.90</td><td>-4.96 4.95</td><td>-4.90</td><td>4.90</td><td>-4.96 4.95</td><td>-4.90</td><td>V</td><td>R L ≥ 10K Ω 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>V O V O high I</td><td>4.99</td><td>-4.998 4.998</td><td>-4.99</td><td>4.99</td><td>-4.998 4.998</td><td>-4.99</td><td>4.99</td><td>-4.998 4.998</td><td>-4.99</td><td>V</td><td>R L = 1M Ω 0 ° C ≤ T A ≤ +70 ° C</td></tr><tr><td>Output Short Circuit Current</td><td>SC</td><td></td><td>15</td><td></td><td></td><td>15</td><td></td><td></td><td>15</td><td></td><td>mA</td><td></td></tr><tr><td>Supply Current</td><td>S</td><td></td><td>5.0</td><td>6.5</td><td></td><td>5.0</td><td>6.5</td><td></td><td>5.0</td><td>6.5</td><td>mA</td><td>V IN = -5V No Load</td></tr><tr><td>Power Dissipation</td><td>P D</td><td></td><td></td><td>65</td><td></td><td></td><td>65</td><td></td><td></td><td>65</td><td>mW</td><td>Both amplifiers, No Load V S = ± 5.0V</td></tr><tr><td>Input Capacitance</td><td>C IN</td><td></td><td>1</td><td></td><td></td><td>1</td><td></td><td></td><td>1</td><td></td><td>pF</td><td></td></tr><tr><td>Bandwidth</td><td>B W</td><td></td><td>2.1</td><td></td><td></td><td>2.1</td><td></td><td></td><td>2.1</td><td></td><td>MHz</td><td></td></tr><tr><td>Slew Rate</td><td>S R</td><td></td><td>5.0</td><td></td><td></td><td>5.0</td><td></td><td></td><td>5.0</td><td></td><td>V/ µ s</td><td>A V = +1 R L = 2.0K Ω</td></tr><tr><td>Rise time</td><td>t r</td><td></td><td>0.1</td><td></td><td></td><td>0.1</td><td></td><td></td><td>0.1</td><td></td><td>µ s</td><td>R L = 2.0K Ω</td></tr><tr><td>Overshoot Factor</td><td></td><td></td><td>15</td><td></td><td></td><td>15</td><td></td><td></td><td>15</td><td></td><td>%</td><td>R L = 2.0K Ω C L = 100pF</td></tr></table></body></html>

You are a deterministic data transformation engine. Your sole task is to convert any HTML, Markdown, or raw text table layout into a strict Entity-Attribute-Value (EAV) format based on structural geometries and semantic continuity.

### CORE DEFINITIONS FOR THIS TASK:
1. **Entity**: The primary subject identifier for the record entry. 
   - In single-data-row horizontal tables, this matches each column header (or a logically combined phrase if headers are fragmented).
   - In pure two-column vertical tables, this is the label string extracted from the first column.
   - In multi-row matrices, this is the most unique primary key string characterizing that specific entry (e.g., a Part Code, Model SKU, Reference ID, or specific Parameter Name).
2. **Attribute**: The metric, conditional parameter, or column header modifying the data point (e.g., "TEST CONDITIONS", "MIN", "TYP", "MAX", "UNIT"). For single-data-row or pure key-value tables lacking secondary modifiers, this column must be set explicitly to the literal string "NULL".
3. **Value**: The exact structural cell content located at the intersection of the Entity and the Attribute.

### SYSTEM CONSTRAINTS & OPERATIONAL LAWS:
- **Strict Data Integrity**: Preserve all original text data exactly as it exists in the input cells. Do NOT modify casing, do NOT clean up spacing, do NOT remove symbols (like *, ±, -), and do NOT truncate units. Copy poorly formatted strings exactly as-is.
- **Empty Cells**: If a data cell is completely empty and cannot be structurally resolved, use the literal string "[Blank]".
- **Output Format**: Output the final result as a clean Markdown table with exactly three columns: | Entity | Attribute | Value |. Do not include conversational filler, introductions, or explanations.

---

## PHASE 1 — STRUCTURAL MAPPING (perform silently, before producing any output)

For any input table, determine the following facts. Do not skip this even for tables that look simple — the mapping is what prevents inconsistent guessing later.

1. **Header depth**: How many stacked header rows exist above the first data row? 
2. **Header hierarchy**: Build the literal tree of header labels, tier by tier, left to right, noting any colspan boundaries.
3. **Data row count**: How many physical data rows exist beneath the header(s)?
4. **Row grouping**: Record any columns using rowspan properties.
5. **Column cardinality scan**: Count distinct non-empty values across all rows per column to identify the primary key axis column.
6. **Advanced Split, Merge & Condensation Scan**: 
   - **Accidental Split Check**: Scan adjacent header columns for single continuous phrases split into separate cells with trailing empty data cells underneath. Flag as "Split Header Anomaly".
   - **Accidental Merge Check**: Scan individual data cells for distinct tokens run together inline with whitespace/symbol boundaries (e.g., a unit next to a numeric value like "°C -40"). Flag as "Merged Cell Anomaly".
   - **Condensed Row Check**: Scan each individual row layout. Check if key descriptor columns contain parallel vertically-stacked text lines or multiple separate text blocks run together within single cells (e.g., "V S V+", "V V", "Line1 Line2"). Count the maximum number of parallel text lines or token stacks ($N$) found inside that row's cells. If $N > 1$, flag the entire row as a "Condensed Row Anomaly" of depth $N$.
   - **CRITICAL - Structural Header Symmetry Check**: Look at repeating column structures (e.g., sequential sibling groups under identical colspans). Check if a single header cell displays a concatenated run-together phrase (e.g., "Max Min" or "Unit Typ") that breaks the symmetry of its neighboring column groups. Flag this cell as a "Contracted Header Anomaly".

---

## PHASE 2 — DERIVING ENTITY / ATTRIBUTE / VALUE FROM THE MAP

Apply these derivations in order. Each derivation is a general procedure, not a table-shape lookup.

**A. Determine the Entity axis:**
- If data row count = 1: If a "Split Header Anomaly" exists, merge them into a single phrase string as the Entity, map the single non-empty data point to Value, and set Attribute = "NULL". Otherwise, each column header is its own Entity with Attribute = "NULL".
- If data row count > 1: The Entity is the value in the highest-cardinality primary key column identified in Phase 1.5, for each row.
  - **Rowspan check**: If the Entity column is rowspanned, propagate or build the Entity as: `<rowspanned label> (<row's own distinguishing value>)`. Never use positional placeholders like "Row1".
  - If exactly two columns exist with no multi-row matrix features, column 1 = Entity, Attribute = "NULL", column 2 = Value.

**B. Determine the Attribute axis:**
- Build each column's Attribute name from the full header hierarchy above it, joining tiers top-to-bottom with `" / "`. 
- **Resolution for Contracted Header Anomalies**: If a cell was flagged in Phase 1.6 as a "Contracted Header Anomaly", decouple the run-together words based on the pattern established by neighboring column groups. Restore the missing structural grid borders and map the respective text segments cleanly to their distinct proper composite attribute layers (e.g., split "Max Min" into its matching sibling columns).
- If a header cell was split due to poor formatting, merge the fragmented cells into one Attribute string.
- Attribute = "NULL" only in the two degenerate cases in 2A (single-row table, or plain two-column key-value table).

**C. Determine the Value axis and resolve merged/condensed rows:**
- Value is the exact cell content at the Entity/Attribute intersection, preserved verbatim.
- **Resolution for Condensed Row Anomalies (Row Unpacking)**: If a row is flagged in Phase 1.6 as a "Condensed Row Anomaly" of depth $N$, you must structurally duplicate this row $N$ times in your EAV processing pipeline before outputting values:
  1. For every cell in this row that contains $N$ vertically stacked text lines or separate space-delimited tokens, separate the cell into $N$ individual sequential data elements. 
  2. For cells in the same row that contain only a single atomic value or are `[Blank]`, replicate that single value or blank space across all $N$ unpacked iterations.
  3. Append a contextual label suffix drawn from the row's own decoupled descriptor tokens to each of the $N$ generated Entity rows to keep them uniquely distinguishable (e.g., `[Entity Name] ([Decoupled Condition Line X])`). Map each unpacked line element to its respective index row.
- **Resolution for Merged Cells**: For individual cells flagged as a "Merged Cell Anomaly", split the string token-by-token based on data type context only if they match distinct targets (e.g., map a unit token and a limit token to their respective distinct attribute rows). If boundaries are ambiguous, keep the entire raw string as one Value and append `" (unparsed-merge)"` to that row's Attribute name.
- Completely empty, structurally unresolvable cells become the literal string `"[Blank]"`.
- If a data cell intentionally spans multiple columns (colspan) covering more than one Attribute, join the covered headers with `"/"` and append `" (Merged)"`.

---

## PHASE 3 — SELF-VERIFICATION (perform silently before returning output)

Before returning the final table, check:
1. **Coverage**: Every original data cell token appears exactly once in the output, either as a Value or explicitly marked `[Blank]`.
2. **Consistency**: Rows sharing the same Entity structure use Attribute names drawn from the same header hierarchy layers.
3. **No fabricated placeholders**: Confirm no Entity or Attribute contains an invented disambiguator not traceable to actual source text.
4. **Uniqueness**: No (Entity, Attribute) pair repeats with two different Values — if this happens, re-verify the "Condensed Row Anomaly" depth tracking or re-apply Entity row suffix disambiguation.

**Escalation**: If verification step 4 fails and cannot be resolved, output the EAV table as far as it can be built, then add one line after the table: `NOTE: rows [x, y] share Entity/Attribute "..." with conflicting values "..." — source table structure is ambiguous.`

In [29]:
TDQEQ_OPENAI_API_KEY="AQ.Ab8RN6J6Q7ocr4aZ8_nbGcsDPMKiePVqG5Y5_L3OmG6mhj5Kpw"
TDQEQ_OPENAI_MODEL="models/gemini-3.5-flash-lite"
TDQEQ_OPENAI_BASE_URL="https://generativelanguage.googleapis.com/v1beta/openai/"

In [231]:
TDQEQ_OPENAI_API_KEY="sk-MuVZaTUtHt7Vnim3wDL71Q"
TDQEQ_OPENAI_MODEL="us.anthropic.claude-sonnet-4-5-20250929-v1:0"
TDQEQ_OPENAI_BASE_URL="http://10.203.12.137:4000"

In [30]:
import openai
import json_repair
import pandas as pd


client = openai.OpenAI(api_key=TDQEQ_OPENAI_API_KEY, base_url=TDQEQ_OPENAI_BASE_URL)

In [31]:
SYSTEM_PROMPT= """
You are a deterministic data transformation engine. Your sole task is to convert a list of JSON objects, each containing an HTML table layout, into a highly optimized, mapped, and nested JSON structure.

### CORE DEFINITIONS FOR THIS TASK:
1. **Primary Entity**: The main subject characterizing a logical record (e.g., a Part Number or ID). 
2. **Shared Attributes**: Columns containing data that apply universally to the Primary Entity (often visually represented by cells spanning multiple rows via `rowspan`).
3. **Variant Attributes (1-to-Many)**: Columns containing distinct sub-records that belong to the Primary Entity.

### INPUT FORMAT:
You will receive a JSON array of objects: `[{"html": "...", "page_number": <int>, "confidence_score": <float>}]`

### OUTPUT FORMAT (Mapped & Nested JSON):
You must output a single JSON array containing one object per table (or merged table). Each object must have:
- `page_number`: The integer (or array of integers if merged).
- `confidence_score`: The float (or minimum float if merged).
- `table_title`: A string extracted from the `class` attribute of the `<table>` tag. If none, use `""`.
- `mapping_scratchpad`: A brief string where you explicitly write out your Chain-of-Thought (normalization steps, cross-page merges, and Primary Key selection) before generating data.
- `column_mapping`: A dictionary where keys are sequential IDs (`"c1"`, `"c2"`, `"c3"`, etc.) and values are the exact verbatim column headers derived from the table hierarchy (join multi-tier headers with " / ").
- `data`: An array of objects representing the extracted entities.

**Data Payload Laws (`data` array):**
- Use the `c_` IDs from your `column_mapping` as the keys for Shared Attributes.
- **Strict Data Integrity**: Preserve all extracted values EXACTLY as they appear in the source HTML. Do not strip whitespace, do not abbreviate words, and do not alter casing.
- **Dynamic Positional Matrix (The 1-to-Many Solution)**: If a Primary Entity contains multiple sub-rows (Variant Attributes), do NOT output standard key-value pairs for those nested variables. Instead:
  1. Define an array named `v_cols` containing the specific column IDs that apply to the nested rows (e.g., `["c8", "c9", "c10"]`).
  2. Define an array named `v` containing an array of string arrays, where each inner array represents one sub-row's verbatim cell values in the exact order dictated by `v_cols`.
- **Empty Cells**: Completely empty cells become `"[Blank]"`. Ignore entirely empty rows.
- **No Conversational Filler**: Output only the final JSON array. Do not include markdown code blocks, introductions, or explanations.

---

## PHASE 0 — PRE-PROCESSING (FILTERING & AGGRESSIVE MERGING)
Before analyzing tables individually, aggressively scan the entire input array from start to finish to detect tables split across document breaks.
- **Layout Table Rejection**: If a table contains no relational data (e.g., just page headers/logos), omit it entirely.
- **CRITICAL - Merge Trigger**: If Table B immediately follows Table A AND meets ANY of these conditions, you MUST merge them:
  1. **Title Match**: They share the exact same non-empty `table_title`.
  2. **Orphan Continuation**: Table B lacks a title, has the exact same column count/geometry as Table A, and acts as a semantic continuation of Table A's data.
- **Merge Action**: Logically fuse their HTML rows into a single continuous table. Table B inherits Table A's headers. Output as a single JSON object.

## PHASE 1 — STRUCTURAL MAPPING & NORMALIZATION (Document in `mapping_scratchpad`)
For each logical table, determine and write down:
1. **Grid Normalization (The Matrix Projection)**: Mentally project the raw HTML into a strictly symmetrical 2D grid to resolve structural anomalies and OCR breakage:
   - **Colspan Resolution**: If a cell has `colspan="X"`, explicitly replicate that cell's value `X` times across the adjacent virtual columns.
   - **Sequential Rowspan Unpacking (Merged Text)**: If a cell has `rowspan="Y"` AND contains multiple distinct strings (separated by spaces or line breaks), evaluate if the number of distinct strings matches `Y`. If so, DO NOT replicate the entire cell value. Instead, split the text and assign one unique string to each of the `Y` virtual rows sequentially.
   - **Standard Rowspan Resolution**: If a cell has `rowspan="Y"` and contains only a single logical value, explicitly replicate that cell's value `Y` times down the virtual column.
   - **Orphaned Fragment Stitching (Shattered Rows)**: Scan for fragmented data rows caused by structural document breaks (e.g., cells containing hanging text or abrupt empty sibling cells). Mentally stitch these fragments vertically to the nearest logical parent row before deriving any values.
   - **Jagged Rows (Missing Cells)**: If a row has fewer `<td>` elements than the header columns, implicitly pad the missing trailing cells with `"[Blank]"`.
2. **Header Tree**: Build the hierarchy of header labels and map them to `c_` IDs.
3. **Primary Entity Inference**: Scan all normalized columns to identify the Primary Key using this weighted heuristic:
   - *Positive Signals*: Headers containing `ID`, `Code`, `SKU`, `Ref`, `Part No`, or `No.`. Cell values with alphanumeric patterns or fixed-length strings. Give massive preference to index 0 or 1.
   - *Negative Constraints*: MUST ignore columns representing continuous metrics (`Price`, `Qty`, `Weight`), dates, or booleans.

## PHASE 2 — DERIVING ENTITIES AND VARIANTS (The Universal Span Rule)
Based on the normalized grid, you must strictly classify every column as either a Shared Attribute or a Variant Attribute before extracting data.

1. **Classify Shared Attributes (Root Keys)**: Look at the complete block of rows belonging to a single Primary Entity. IF AND ONLY IF a column contains exactly ONE unique value that spans the ENTIRE block (e.g., a single `rowspan` that covers every sub-row perfectly), it is a Shared Attribute. Assign it directly to the root entity object using its `c_` ID.
2. **Classify Variant Attributes (Matrix Keys)**: If a column changes value at ANY point within the Primary Entity's block (e.g., it contains two different vertically stacked `rowspan` cells, or distinct sub-row values), it is a Variant Attribute. It CANNOT be a root key. You MUST assign its column ID to the `v_cols` array.
3. **Construct the Matrix**: Iterate through every sub-row of the Primary Entity. For every column identified as a Variant Attribute, append its verbatim cell value to the `v` array in the exact order dictated by `v_cols`. Do not duplicate sub-rows unless explicitly unpacked during Phase 1.

## PHASE 3 — SELF-VERIFICATION 
Check each table's result before returning the final JSON:
1. **Coverage**: Every data cell from the normalized grid appears exactly once.
2. **Symmetry**: Ensure that every string array inside `v` contains the exact same number of elements as the `v_cols` array. 
**Escalation**: If verification fails for specific rows (due to ambiguous source structure), completely **DROP** those broken rows from the `data` array so they do not pollute the output. Add a string to the `"note"` key at the root of the table's JSON explaining which rows were dropped and why.
"""

In [58]:
s= [{'page_number': 0,
  'caption': '3) Superior power ratings. 4) ROHM resistors have obtained ISO9001 / IATF16949 certification. 5) Corresponds to AEC-Q200. ●Products list',
  'detection_confidence': 0.985,
  'html': '<html><body><table><tr><td rowspan=2 colspan=1>Part No.</td><td rowspan=1 colspan=2>Size</td><td rowspan=2 colspan=1>Rated power (W)</td><td rowspan=2 colspan=1>Rated ambient temperature (°C)</td><td rowspan=2 colspan=1>Rated terminal temperature (°C)</td><td rowspan=2 colspan=1>Limiting element voltage (V)</td><td rowspan=2 colspan=1>Temperature coefficient (ppm/ °C)</td><td rowspan=2 colspan=1>Resistance tolerance (%)</td><td rowspan=2 colspan=1>Resistance range (Ω)</td><td rowspan=2 colspan=1>Operating temperature range (°C)</td><td rowspan=2 colspan=1>Automotive Grade Available (AEC-Q200)</td></tr><tr><td rowspan=1 colspan=1>(mm)</td><td rowspan=1 colspan=1>(inch)</td></tr><tr><td rowspan=4 colspan=1>ESR01</td><td rowspan=4 colspan=1>1005</td><td rowspan=4 colspan=1>0402</td><td rowspan=4 colspan=1>0.2</td><td rowspan=4 colspan=1>70</td><td rowspan=4 colspan=1>-</td><td rowspan=4 colspan=1>50</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>10 ≦ R&lt;1M    (E24/96 series)</td><td rowspan=4 colspan=1>-55 ～ +155</td><td rowspan=4 colspan=1>Yes</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1M ≦ R ≦ 2.2M  (E24 series)</td></tr><tr><td rowspan=1 colspan=1>+500/-250</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1 ≦ R&lt;10     (E24 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>10 ≦ R ≦ 10M   (E24 series)</td></tr><tr><td rowspan=7 colspan=1>ESR03</td><td rowspan=7 colspan=1>1608</td><td rowspan=7 colspan=1>0603</td><td rowspan=7 colspan=1>0.33</td><td rowspan=7 colspan=1>70</td><td rowspan=4 colspan=1>130</td><td rowspan=7 colspan=1>150</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D ( ±0.5% )</td><td rowspan=1 colspan=1>10 ≦ R ≦ 1k    (E24/96 series)</td><td rowspan=7 colspan=1>-55 ～ +155</td><td rowspan=7 colspan=1>Yes</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1 ≦ R&lt;10     (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>10 ≦ R ≦ 1k    (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1 ≦ R ≦ 1k     (E24 series)</td></tr><tr><td rowspan=3 colspan=1>110</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D ( ±0.5% )</td><td rowspan=1 colspan=1>1k&lt;R ≦ 1M    (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1k&lt;R ≦ 10M   (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1k&lt;R ≦ 10M   (E24 series)</td></tr><tr><td rowspan=6 colspan=1>ESR10</td><td rowspan=6 colspan=1>2012</td><td rowspan=6 colspan=1>0805</td><td rowspan=3 colspan=1>0.5</td><td rowspan=6 colspan=1>70</td><td rowspan=3 colspan=1>115</td><td rowspan=6 colspan=1>150</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D ( ±0.5% )</td><td rowspan=1 colspan=1>10 ≦ R&lt;1k     (E24/96 series)</td><td rowspan=6 colspan=1>-55 ～ +155</td><td rowspan=6 colspan=1>Yes</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1 ≦ R&lt;1k     (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1 ≦ R&lt;1k     (E24 series)</td></tr><tr><td rowspan=3 colspan=1>0.4</td><td rowspan=3 colspan=1>125</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D ( ±0.5% )</td><td rowspan=1 colspan=1>1k ≦ R ≦ 1M   (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1k ≦ R ≦ 10M   (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1k ≦ R ≦ 10M   (E24 series)</td></tr><tr><td rowspan=6 colspan=1>ESR18</td><td rowspan=6 colspan=1>3216</td><td rowspan=6 colspan=1>1206</td><td rowspan=3 colspan=1>0.75</td><td rowspan=6 colspan=1>70</td><td rowspan=3 colspan=1>105</td><td rowspan=6 colspan=1>200</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D ( ±0.5% )</td><td rowspan=1 colspan=1>10 ≦ R&lt;1k     (E24/96 series)</td><td rowspan=6 colspan=1>-55 ～ +155</td><td rowspan=6 colspan=1>Yes</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1 ≦ R&lt;1k     (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1 ≦ R&lt;1k     (E24 series)</td></tr><tr><td rowspan=3 colspan=1>0.5</td><td rowspan=3 colspan=1>125</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D ( ±0.5% )</td><td rowspan=1 colspan=1>1k ≦ R ≦ 1M   (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1k ≦ R ≦ 10M   (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1k ≦ R ≦ 10M   (E24 series)</td></tr><tr><td rowspan=3 colspan=1>ESR25</td><td rowspan=3 colspan=1>3225</td><td rowspan=3 colspan=1>1210</td><td rowspan=3 colspan=1>1</td><td rowspan=3 colspan=1>70</td><td rowspan=3 colspan=1>95</td><td rowspan=3 colspan=1>200</td><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>D( ±0.5% )</td><td rowspan=1 colspan=1>10 ≦ R ≦ 1M   (E24/96 series)</td><td rowspan=3 colspan=1>-55 ～ +155</td><td rowspan=3 colspan=1>Yes</td></tr><tr><td rowspan=1 colspan=1>±100</td><td rowspan=1 colspan=1>F ( ±1% )</td><td rowspan=1 colspan=1>1 ≦ R ≦ 10M   (E24/96 series)</td></tr><tr><td rowspan=1 colspan=1>±200</td><td rowspan=1 colspan=1>J ( ±5% )</td><td rowspan=1 colspan=1>1 ≦ R ≦ 10M   (E24 series)</td></tr></table></body></html>'},
 {'page_number': 0,
  'caption': 'Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10 EZP',
  'detection_confidence': 0.964,
  'html': '<html><body><table><tr><td rowspan=1 colspan=4>Packaging specifications code</td></tr><tr><td rowspan=1 colspan=1>Part No.</td><td rowspan=1 colspan=1>Code</td><td rowspan=1 colspan=1>Packaging specifications</td><td rowspan=1 colspan=1>Quantity / Reel</td></tr><tr><td rowspan=1 colspan=1>ESR01</td><td rowspan=1 colspan=1>MZP</td><td rowspan=1 colspan=1>Paper tape ( 2mmPitch)</td><td rowspan=1 colspan=1>10,000</td></tr><tr><td rowspan=1 colspan=1>ESR03</td><td rowspan=1 colspan=1>EZP</td><td rowspan=1 colspan=1>Paper tape ( 4mmPitch)</td><td rowspan=1 colspan=1>5,000</td></tr><tr><td rowspan=1 colspan=1>ESR10</td><td rowspan=1 colspan=1>EZP</td><td rowspan=1 colspan=1>Paper tape ( 4mmPitch)</td><td rowspan=1 colspan=1>5,000</td></tr><tr><td rowspan=1 colspan=1>ESR18</td><td rowspan=1 colspan=1>EZP</td><td rowspan=1 colspan=1>Paper tape ( 4mmPitch)</td><td rowspan=1 colspan=1>5,000</td></tr><tr><td rowspan=1 colspan=1>ESR25</td><td rowspan=1 colspan=1>JZP</td><td rowspan=1 colspan=1>Embossed tape ( 4mmPitch)</td><td rowspan=1 colspan=1>4,000</td></tr></table></body></html>'},
 {'page_number': 0,
  'caption': 'Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10',
  'detection_confidence': 0.917,
  'html': '<html><body><table class="Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10"><tr><td>Size</td><td>(mm)</td><td>[inch]</td></tr><tr><td>01 03</td><td>(1005) (1608)</td><td>[0402] [0603]</td></tr><tr><td>10</td><td>(2012)</td><td>[0805]</td></tr><tr><td></td><td></td><td></td></tr><tr><td>18 25</td><td>(3216) (3225)</td><td>[1206] [1210]</td></tr></table></body></html>'},
 {'page_number': 0,
  'caption': 'Rated voltage = E24 : Standard products, ●Part Number ESR',
  'detection_confidence': 0.899,
  'html': '<html><body><table class="Rated voltage = E24 : Standard products, ●Part Number ESR"><tr><td>Part No.</td></tr><tr><td>ESR Anti-surge</td></tr><tr><td></td></tr><tr><td>chip resistors</td></tr></table></body></html>'},
 {'page_number': 0,
  'caption': 'Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10 EZP J 100',
  'detection_confidence': 0.712,
  'html': '<html><body><table class="Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10 EZP J 100"><tr><td colspan="3">Nominal resistance</td></tr><tr><td colspan="3">Resistance code, 3 or 4 digits.</td></tr><tr><td>Resistance tolerance</td><td></td><td>Resistance code</td></tr><tr><td>D,F</td><td>:</td><td>4 digits</td></tr><tr><td>J EX)</td><td>:</td><td>3 digits</td></tr><tr><td>1Ω =</td><td>1R00 1R0</td><td>(±1%) (±5%)</td></tr><tr><td>9.1Ω =</td><td>9R10 9R1</td><td>(±1%) (±5%)</td></tr><tr><td>10Ω =</td><td>10R0</td><td>(±0.5%,±1%)</td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td>100</td><td>(±5%)</td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td>1MΩ</td><td></td><td></td></tr><tr><td></td><td>= 1004</td><td>(±0.5%,±1%)</td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td>(±5%)</td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td>105</td><td></td></tr></table></body></html>'},
 {'page_number': 0,
  'caption': 'Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10 EZP J',
  'detection_confidence': 0.91,
  'html': '<html><body><table class="Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10 EZP J"><tr><td>Resistance tolerance</td></tr><tr><td>D(±0.5%) F (±1%)</td></tr></table></body></html>'}]

In [75]:
user_message=f"""
{s[-2]}
"""

In [82]:
response = client.chat.completions.create(
    model=TDQEQ_OPENAI_MODEL,
    messages=[
        {"role": "system", "content": SYSTEM_PROMPT.strip()},
        {"role": "user", "content": user_message.strip()},
    ],
    temperature=0.0,
)

input_tokens = response.usage.prompt_tokens
output_tokens = response.usage.completion_tokens
total_tokens = response.usage.total_tokens

print(f"Input Tokens: {input_tokens}")
print(f"Output Tokens: {output_tokens}")
print(f"Total Tokens: {total_tokens}")

Input Tokens: 2250
Output Tokens: 541
Total Tokens: 2791

In [77]:
content = response.choices[0].message.content

In [78]:
json_data= json_repair.loads(content)

In [21]:
json_data=[
  {
    "page_number": 0,
    "confidence_score": 0.985,
    "table_title": "",
    "mapping_scratchpad": "Normalized grid by resolving rowspans for Part No, Size, Rated power, Rated ambient temperature, Rated terminal temperature, Limiting element voltage, Operating temperature range, and Automotive Grade. Variant attributes identified as Temperature coefficient, Resistance tolerance, and Resistance range. ESR03, ESR10, and ESR18 contain nested sub-groups for Rated power/terminal temperature, which are treated as part of the variant matrix.",
    "column_mapping": {
      "c1": "Part No.",
      "c2": "Size / (mm)",
      "c3": "Size / (inch)",
      "c4": "Rated power (W)",
      "c5": "Rated ambient temperature (°C)",
      "c6": "Rated terminal temperature (°C)",
      "c7": "Limiting element voltage (V)",
      "c8": "Temperature coefficient (ppm/ °C)",
      "c9": "Resistance tolerance (%)",
      "c10": "Resistance range (Ω)",
      "c11": "Operating temperature range (°C)",
      "c12": "Automotive Grade Available (AEC-Q200)"
    },
    "data": [
      {
        "c1": "ESR01",
        "c2": "1005",
        "c3": "0402",
        "c4": "0.2",
        "c5": "70",
        "c6": "-",
        "c7": "50",
        "c11": "-55 ～ +155",
        "c12": "Yes",
        "v_cols": ["c8", "c9", "c10"],
        "v": [
          ["±100", "F ( ±1% )", "10 ≦ R<1M    (E24/96 series)"],
          ["±100", "F ( ±1% )", "1M ≦ R ≦ 2.2M  (E24 series)"],
          ["+500/-250", "J ( ±5% )", "1 ≦ R<10     (E24 series)"],
          ["±200", "J ( ±5% )", "10 ≦ R ≦ 10M   (E24 series)"]
        ]
      },
      {
        "c1": "ESR03",
        "c2": "1608",
        "c3": "0603",
        "c4": "0.33",
        "c5": "70",
        "c7": "150",
        "c11": "-55 ～ +155",
        "c12": "Yes",
        "v_cols": ["c6", "c8", "c9", "c10"],
        "v": [
          ["130", "±100", "D ( ±0.5% )", "10 ≦ R ≦ 1k    (E24/96 series)"],
          ["130", "±200", "F ( ±1% )", "1 ≦ R<10     (E24/96 series)"],
          ["130", "±100", "F ( ±1% )", "10 ≦ R ≦ 1k    (E24/96 series)"],
          ["130", "±200", "J ( ±5% )", "1 ≦ R ≦ 1k     (E24 series)"],
          ["110", "±100", "D ( ±0.5% )", "1k<R ≦ 1M    (E24/96 series)"],
          ["110", "±100", "F ( ±1% )", "1k<R ≦ 10M   (E24/96 series)"],
          ["110", "±200", "J ( ±5% )", "1k<R ≦ 10M   (E24 series)"]
        ]
      },
      {
        "c1": "ESR10",
        "c2": "2012",
        "c3": "0805",
        "c5": "70",
        "c7": "150",
        "c11": "-55 ～ +155",
        "c12": "Yes",
        "v_cols": ["c4", "c6", "c8", "c9", "c10"],
        "v": [
          ["0.5", "115", "±100", "D ( ±0.5% )", "10 ≦ R<1k     (E24/96 series)"],
          ["0.5", "115", "±100", "F ( ±1% )", "1 ≦ R<1k     (E24/96 series)"],
          ["0.5", "115", "±200", "J ( ±5% )", "1 ≦ R<1k     (E24 series)"],
          ["0.4", "125", "±100", "D ( ±0.5% )", "1k ≦ R ≦ 1M   (E24/96 series)"],
          ["0.4", "125", "±100", "F ( ±1% )", "1k ≦ R ≦ 10M   (E24/96 series)"],
          ["0.4", "125", "±200", "J ( ±5% )", "1k ≦ R ≦ 10M   (E24 series)"]
        ]
      },
      {
        "c1": "ESR18",
        "c2": "3216",
        "c3": "1206",
        "c5": "70",
        "c7": "200",
        "c11": "-55 ～ +155",
        "c12": "Yes",
        "v_cols": ["c4", "c6", "c8", "c9", "c10"],
        "v": [
          ["0.75", "105", "±100", "D ( ±0.5% )", "10 ≦ R<1k     (E24/96 series)"],
          ["0.75", "105", "±100", "F ( ±1% )", "1 ≦ R<1k     (E24/96 series)"],
          ["0.75", "105", "±200", "J ( ±5% )", "1 ≦ R<1k     (E24 series)"],
          ["0.5", "125", "±100", "D ( ±0.5% )", "1k ≦ R ≦ 1M   (E24/96 series)"],
          ["0.5", "125", "±100", "F ( ±1% )", "1k ≦ R ≦ 10M   (E24/96 series)"],
          ["0.5", "125", "±200", "J ( ±5% )", "1k ≦ R ≦ 10M   (E24 series)"]
        ]
      },
      {
        "c1": "ESR25",
        "c2": "3225",
        "c3": "1210",
        "c4": "1",
        "c5": "70",
        "c6": "95",
        "c7": "200",
        "c11": "-55 ～ +155",
        "c12": "Yes",
        "v_cols": ["c8", "c9", "c10"],
        "v": [
          ["±100", "D( ±0.5% )", "10 ≦ R ≦ 1M   (E24/96 series)"],
          ["±100", "F ( ±1% )", "1 ≦ R ≦ 10M   (E24/96 series)"],
          ["±200", "J ( ±5% )", "1 ≦ R ≦ 10M   (E24 series)"]
        ]
      }
    ]
  }
]

In [83]:
def unpack_json_to_output(data):
    output = []
    
    for table in data:
        # 1. Grab the original top-level fields
        page_number = table.get("page_number")
        confidence_score = table.get("confidence_score")
        table_title = table.get("table_title")
        column_mapping = table.get("column_mapping", {})
        
        unpacked_rows = []
        
        for row in table.get("data", []):
            # 2. Extract base/shared attributes (any key starting with 'c')
            base_attrs = {k: v for k, v in row.items() if k.startswith("c")}
            
            v_cols = row.get("v_cols", [])
            v_data = row.get("v", [])
            
            if v_data:
                # 3. If variants exist, merge each variant with the base attributes
                for variant_row in v_data:
                    combined = base_attrs.copy()
                    # Map the list of values to their corresponding 'cX' keys
                    for i, col_key in enumerate(v_cols):
                        combined[col_key] = variant_row[i]
                    
                    # 4. Translate 'cX' keys to human-readable names using column_mapping
                    translated_row = {
                        column_mapping.get(k, k): v for k, v in combined.items()
                    }
                    unpacked_rows.append(translated_row)
            else:
                # 5. If no variants exist, just translate the base attributes
                translated_row = {
                    column_mapping.get(k, k): v for k, v in base_attrs.items()
                }
                unpacked_rows.append(translated_row)
        
        # 6. Assemble the final object structure for this table
        output.append({
            "page_number": page_number,
            "confidence_score": confidence_score,
            "table_title": table_title,
            "rows": unpacked_rows
        })
                
    return output

In [79]:
flat_rows = unpack_json_to_output(json_data)
flat_rows

[{'page_number': 0,
  'confidence_score': 0.712,
  'table_title': 'Rated voltage = Rated power × Resistance E24 : Standard products, E96: Build to order. ●Part Number Description ESR 10 EZP J 100',
  'rows': []}]

In [73]:
import pandas as pd

df= pd.DataFrame(flat_rows[4]['rows'])
df

Empty DataFrame
Columns: []
Index: []

In [5]:
df

,Part No.,Size / (mm),Size / (inch),Rated power (W),Rated ambient temperature (°C),Rated terminal temperature (°C),Limiting element voltage (V),Operating temperature range (°C),Automotive Grade Available (AEC-Q200),Temperature coefficient (ppm/ °C),Resistance tolerance (%),Resistance range (Ω)
0,ESR01,1005,0402,0.2,70,-,50,-55 ～ +155,Yes,±100,F ( ±1% ),10 ≦ R<1M (E24/96 series)
1,ESR01,1005,0402,0.2,70,-,50,-55 ～ +155,Yes,±100,F ( ±1% ),1M ≦ R ≦ 2.2M (E24 series)
2,ESR01,1005,0402,0.2,70,-,50,-55 ～ +155,Yes,+500/-250,J ( ±5% ),1 ≦ R<10 (E24 series)
3,ESR01,1005,0402,0.2,70,-,50,-55 ～ +155,Yes,±200,J ( ±5% ),10 ≦ R ≦ 10M (E24 series)
4,ESR03,1608,0603,0.33,70,130,150,-55 ～ +155,Yes,±100,D ( ±0.5% ),10 ≦ R ≦ 1k (E24/96 series)
5,ESR03,1608,0603,0.33,70,130,150,-55 ～ +155,Yes,±200,F ( ±1% ),1 ≦ R<10 (E24/96 series)
6,ESR03,1608,0603,0.33,70,130,150,-55 ～ +155,Yes,±100,F ( ±1% ),10 ≦ R ≦ 1k (E24/96 series)
7,ESR03,1608,0603,0.33,70,130,150,-55 ～ +155,Yes,±200,J ( ±5% ),1 ≦ R ≦ 1k (E24 series)
8,ESR03,1608,0603,0.33,70,110,150,-55 ～ +155,Yes,±100,D ( ±0.5% ),1k<R ≦ 1M (E24/96 series)
9,ESR03,1608,0603,0.33,70,110,150,-55 ～ +155,Yes,±100,F ( ±1% ),1k<R ≦ 10M (E24/96 series)
10,ESR03,1608,0603,0.33,70,110,150,-55 ～ +155,Yes,±200,J ( ±5% ),1k<R ≦ 10M (E24 series)
11,ESR10,2012,0805,0.5,70,115,150,-55 ～ +155,Yes,±100,D ( ±0.5% ),10 ≦ R<1k (E24/96 series)
12,ESR10,2012,0805,0.5,70,115,150,-55 ～ +155,Yes,±100,F ( ±1% ),1 ≦ R<1k (E24/96 series)
13,ESR10,2012,0805,0.5,70,115,150,-55 ～ +155,Yes,±200,J ( ±5% ),1 ≦ R<1k (E24 series)
14,ESR10,2012,0805,0.4,70,125,150,-55 ～ +155,Yes,±100,D ( ±0.5% ),1k ≦ R ≦ 1M (E24/96 series)
15,ESR10,2012,0805,0.4,70,125,150,-55 ～ +155,Yes,±100,F ( ±1% ),1k ≦ R ≦ 10M (E24/96 series)
16,ESR10,2012,0805,0.4,70,125,150,-55 ～ +155,Yes,±200,J ( ±5% ),1k ≦ R ≦ 10M (E24 series)
17,ESR18,3216,1206,0.75,70,105,200,-55 ～ +155,Yes,±100,D ( ±0.5% ),10 ≦ R<1k (E24/96 series)
18,ESR18,3216,1206,0.75,70,105,200,-55 ～ +155,Yes,±100,F ( ±1% ),1 ≦ R<1k (E24/96 series)
19,ESR18,3216,1206,0.75,70,105,200,-55 ～ +155,Yes,±200,J ( ±5% ),1 ≦ R<1k (E24 series)
20,ESR18,3216,1206,0.5,70,125,200,-55 ～ +155,Yes,±100,D ( ±0.5% ),1k ≦ R ≦ 1M (E24/96 series)
21,ESR18,3216,1206,0.5,70,125,200,-55 ～ +155,Yes,±100,F ( ±1% ),1k ≦ R ≦ 10M (E24/96 series)
22,ESR18,3216,1206,0.5,70,125,200,-55 ～ +155,Yes,±200,J ( ±5% ),1k ≦ R ≦ 10M (E24 series)
23,ESR25,3225,1210,1,70,95,200,-55 ～ +155,Yes,±100,D( ±0.5% ),10 ≦ R ≦ 1M (E24/96 series)
24,ESR25,3225,1210,1,70,95,200,-55 ～ +155,Yes,±100,F ( ±1% ),1 ≦ R ≦ 10M (E24/96 series)
25,ESR25,3225,1210,1,70,95,200,-55 ～ +155,Yes,±200,J ( ±5% ),1 ≦ R ≦ 10M (E24 series)

In [ ]:
{
    "Part No.":"ESR01",
    "Size / (mm)":"1005",
    "Size / (inch)":"0402",
    "Rated power (W)":"0.2",
    "Rated ambient temperature (°C)":"70",
    "Rated terminal temperature (°C)":"-",
    "Limiting element voltage (V)":"50",
    "Temperature coefficient (ppm/ °C)":"±100",
    "Resistance tolerance (%)":"F ( ±1% )",
    "Resistance range (Ω)":"10 ≦ R<1M    (E24/96 series)",
    "Operating temperature range (°C)":"-55 ～ +155",
    "Automotive Grade Available (AEC-Q200)":"Yes"

}

In [47]:
print(content)

[
  {
    "page_number": 0,
    "confidence_score": 0.969,
    "table_title": "",
    "mapping_scratchpad": "Identified single-row table. Primary Entity is 'Conductor(s)'. All columns are treated as Shared Attributes as there is only one row of data. No variant attributes present. Mapping: c1=Element, c2=No. of Elements, c3=Size, c4=Stranding, c5=Material.",
    "column_mapping": {
      "c1": "Element",
      "c2": "No. of Elements",
      "c3": "Size",
      "c4": "Stranding",
      "c5": "Material"
    },
    "data": [
      {
        "c1": "Conductor(s)",
        "c2": "4",
        "c3": "22",
        "c4": "Solid",
        "c5": "BC - Bare Copper"
      }
    ]
  }
]

In [21]:
def unpack_optimized_to_eav(llm_output, primary_entity_id="c1"):
    """
    Converts the token-optimized nested LLM JSON back into a flat EAV list.
    
    :param llm_output: The JSON array output from the LLM.
    :param primary_entity_id: The dictionary key representing the Primary Entity (usually "c1").
    :return: A list of strict EAV dictionaries.
    """
    unpacked_eav_data = []

    # Iterate over each extracted table in the payload
    for table in llm_output:
        mapping = table.get("column_mapping", {})
        data = table.get("data", [])
        
        # Resolve the actual name of the Primary Entity (e.g., "Part No.")
        entity_header = mapping.get(primary_entity_id, "Primary_ID")
        
        for record in data:
            # Get the actual ID value for this row (e.g., "ESR01")
            entity_id = record.get(primary_entity_id, "Unknown")
            
            # Step 1: Unpack Shared Attributes (The root-level 'c_' keys)
            for key, value in record.items():
                if key.startswith("c") and key != primary_entity_id:
                    attribute_name = mapping.get(key, key) # Lookup real column name
                    unpacked_eav_data.append({
                        "Entity_Header": entity_header,
                        "Entity_ID": entity_id,
                        "Attribute": attribute_name,
                        "Value": value
                    })
            
            # Step 2: Unpack Variant Attributes (The 1-to-many matrix)
            v_cols = record.get("v_cols", [])
            v_matrix = record.get("v", [])
            
            for row in v_matrix:
                for col_index, cell_value in enumerate(row):
                    col_id = v_cols[col_index]
                    attribute_name = mapping.get(col_id, col_id) # Lookup real column name
                    
                    unpacked_eav_data.append({
                        "Entity_Header": entity_header,
                        "Entity_ID": entity_id,
                        "Attribute": attribute_name,
                        "Value": cell_value
                    })

    return unpacked_eav_data


# --- EXAMPLE USAGE ---

# Assume `optimized_json_payload` is the dictionary returned by your LLM API
# flat_eav_dataset = unpack_optimized_to_eav(optimized_json_payload)
# print(json.dumps(flat_eav_dataset, indent=2))

In [23]:

j =json_repair.loads(content)

In [25]:
cc= unpack_optimized_to_eav(j)

In [26]:
cc

[{'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Size / (mm)',
  'Value': '1005'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Size / (inch)',
  'Value': '0402'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Rated power (W)',
  'Value': '0.2'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Rated ambient temperature (°C)',
  'Value': '70'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Rated terminal temperature (°C)',
  'Value': '-'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Limiting element voltage (V)',
  'Value': '50'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Operating temperature range (°C)',
  'Value': '-55 ～ +155'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Automotive Grade Available (AEC-Q200)',
  'Value': 'Yes'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R<1M    (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1M ≦ R ≦ 2.2M  (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '+500/-250'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R<10     (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR01',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R ≦ 10M   (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Size / (mm)',
  'Value': '1608'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Size / (inch)',
  'Value': '0603'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Rated power (W)',
  'Value': '0.33'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Rated ambient temperature (°C)',
  'Value': '70'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Rated terminal temperature (°C)',
  'Value': '130'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Limiting element voltage (V)',
  'Value': '150'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Operating temperature range (°C)',
  'Value': '-55 ～ +155'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Automotive Grade Available (AEC-Q200)',
  'Value': 'Yes'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D ( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R ≦ 1k    (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R<10     (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R ≦ 1k    (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R ≦ 1k     (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D ( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k<R ≦ 1M    (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k<R ≦ 10M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR03',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k<R ≦ 10M   (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Size / (mm)',
  'Value': '2012'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Size / (inch)',
  'Value': '0805'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Rated power (W)',
  'Value': '0.5'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Rated ambient temperature (°C)',
  'Value': '70'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Rated terminal temperature (°C)',
  'Value': '115'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Limiting element voltage (V)',
  'Value': '150'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Operating temperature range (°C)',
  'Value': '-55 ～ +155'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Automotive Grade Available (AEC-Q200)',
  'Value': 'Yes'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D ( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R<1k     (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R<1k     (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R<1k     (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D ( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k ≦ R ≦ 1M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k ≦ R ≦ 10M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR10',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k ≦ R ≦ 10M   (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Size / (mm)',
  'Value': '3216'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Size / (inch)',
  'Value': '1206'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Rated power (W)',
  'Value': '0.75'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Rated ambient temperature (°C)',
  'Value': '70'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Rated terminal temperature (°C)',
  'Value': '105'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Limiting element voltage (V)',
  'Value': '200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Operating temperature range (°C)',
  'Value': '-55 ～ +155'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Automotive Grade Available (AEC-Q200)',
  'Value': 'Yes'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D ( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R<1k     (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R<1k     (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R<1k     (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D ( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k ≦ R ≦ 1M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k ≦ R ≦ 10M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR18',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1k ≦ R ≦ 10M   (E24 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Size / (mm)',
  'Value': '3225'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Size / (inch)',
  'Value': '1210'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Rated power (W)',
  'Value': '1'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Rated ambient temperature (°C)',
  'Value': '70'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Rated terminal temperature (°C)',
  'Value': '95'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Limiting element voltage (V)',
  'Value': '200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Operating temperature range (°C)',
  'Value': '-55 ～ +155'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Automotive Grade Available (AEC-Q200)',
  'Value': 'Yes'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'D( ±0.5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Resistance range (Ω)',
  'Value': '10 ≦ R ≦ 1M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±100'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'F ( ±1% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R ≦ 10M   (E24/96 series)'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Temperature coefficient (ppm/ °C)',
  'Value': '±200'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Resistance tolerance (%)',
  'Value': 'J ( ±5% )'},
 {'Entity_Header': 'Part No.',
  'Entity_ID': 'ESR25',
  'Attribute': 'Resistance range (Ω)',
  'Value': '1 ≦ R ≦ 10M   (E24 series)'}]

In [29]:
df= pd.DataFrame(cc)

In [ ]:
dfs=[]
for i in [cc]:
     
    df= pd.DataFrame(i['eav_data'])
    # df['page_number']= ','.join([str(k) for k in i['page_number']]) if isinstance(i['page_number'], list) else str(i['page_number'])
    # df['confidence_score']= i['confidence_score']
    # df['table_title']= i['table_title']

    dfs.append(df)

TypeError: list indices must be integers or slices, not str

In [30]:
df.to_excel("output12.xlsx", index=False)